{
 "title": "Torrents",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "level", "query": "warning,error" },
   {
    "name": "mountpoint",
    "query": "/srv/movies,/srv/music,/srv/series"
   },
   { "name": "torrent", "query": { "query": "deluge_torrent_done_total" } }
  ]
 },
 "panels": [
  { "title": "Torrent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$mountpoint Used Space",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "repeat": "mountpoint",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"$mountpoint\"} - node_filesystem_free_bytes{mountpoint=\"$mountpoint\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"$mountpoint\"}",
     "legendFormat": "__auto"
    },
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "expression": "$B*0.95",
     "type": "math"
    }
   ]
  },
  {
   "title": "Torrent States",
   "type": "stat",
   "gridPos": { "h": 15, "w": 4, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "deluge_torrents", "legendFormat": "{{state}}" }
   ]
  },
  {
   "title": "In Progress Downloads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "deluge_torrent_done_total{state=\"downloading\"} / deluge_torrent_size_total{state=\"downloading\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Last Download",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "deluge_torrent_time_since_download{state=\"downloading\",name=~\"$torrent\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Last Seen Completed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time()-deluge_torrent_last_seen_complete{state=\"downloading\",name=~\"$torrent\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "VPN Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"tun1\"}[1m])",
     "legendFormat": "in"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"tun1\"}[1m])",
     "legendFormat": "out"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Services Up",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "netdata_systemd_service_unit_state_state_average{unit_name=~\"deluged|delugeweb|openvpn.+\",dimension=\"active\"}",
     "legendFormat": "{{unit_name}}"
    }
   ]
  },
  {
   "title": "Deluge Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 17 },
   "targets": [
    {
     "expr": "{unit=\"deluged.service\",level=~\"$level\"}"
    }
   ]
  },
  {
   "title": "Latest External IPs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "{unit=\"deluged.service\"} |= \"on_alert_external_ip\" | regexp \".+on_alert_external_ip: (?P<ip>.+)\" | line_format \"{{.ip}}\""
    }
   ]
  },
  {
   "title": "Latest Interface IPs",
   "type": "logs",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 21 },
   "targets": [
    {
     "expr": "{unit=~\"openvpn.+.service\"} |= \"config -s listen_interface\" | pattern \"<_> listen_interface <ip>'\" | line_format \"{{.ip}}\""
    }
   ]
  },
  {
   "title": "VPN Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 16, "x": 8, "y": 26 },
   "targets": [
    {
     "expr": "{unit=~\"openvpn.+.service\",level=~\"$level\"}"
    }
   ]
  }
 ]
}