{
 "title": "Node Health",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(up,hostname)" } }
  ]
 },
 "panels": [
  { "title": "${hostname}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "OS Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_os_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{hostname=~\"$hostname\"}",
     "legendFormat": "{{chip}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "ZFS Pools",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "hostname",
   "targets": [
    {
     "expr": "node_zfs_zpool_state{hostname=~\"$hostname\", state=\"online\"} > 0",
     "legendFormat": "{{zpool}} - {{state}}"
    }
   ]
  },
  {
   "title": "Certificate Remaining Validity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ssl_certificate_expiry_seconds",
     "legendFormat": "{{exported_hostname}}: {{subject}} {{path}}"
    }
   ]
  },
  {
   "title": "Operating Years",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "years" } },
   "targets": [
    {
     "expr": "scrutiny_smart_power_on_hours{hostname=~\"$hostname\"} / (24 * 365)",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Filesystem Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "(1 - $A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Operating Years",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "scrutiny_smart_power_on_hours{hostname=~\"$hostname\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  },
  {
   "title": "Disk Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "scrutiny_device_info{hostname=~\"$hostname\"}",
     "legendFormat": "{{device_name}}"
    }
   ]
  }
 ]
}