{
 "title": "Scraping Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostname", "query": { "query": "label_values(up,hostname)" } }
  ]
 },
 "panels": [
  {
   "title": "Exporter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=~\"prometheus-.*-exporter.service\"}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(net_conntrack_dialer_conn_failed_total{hostname=~\"$hostname\"}[2m]) > 0",
     "legendFormat": "{{dialer_name}} - {{reason}}"
    }
   ]
  },
  {
   "title": "Scraping jobs",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "prometheus_sd_discovered_targets{hostname=~\"$hostname\"}",
     "legendFormat": "{{config}}"
    },
    {
     "expr": "label_replace(increase((sum by(dialer_name) (net_conntrack_dialer_conn_failed_total{hostname=~\"$hostname\"}))[15m:1m]), \"config\", \"$1\", \"dialer_name\", \"(.*)\")",
     "legendFormat": "{{dialer_name}}"
    }
   ]
  }
 ]
}