{
 "title": "Backups",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(systemd_unit_state{name=~\".*backup.*\", name=~\".*.service\", name!~\".*restore.*\", name!~\".*pre.service\"},name)"
    }
   },
   {
    "name": "mountpoints",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes,mountpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Backup Jobs in the Past Week",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(systemd_unit_state{name=~\"[[job]].service\", state=\"activating\"}[7d])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(systemd_unit_state{name=~\"[[job]].service\", state=\"failed\"}[7d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "targets": [
    {
     "expr": "systemd_timer_next_trigger_seconds{name=~\"$job.timer\"} * 1000",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Backups Jobs",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max(systemd_unit_state{name=~\"$job.service\", state=\"activating\"} > 0 or on(name) label_replace(clamp(systemd_timer_last_trigger_seconds{name=~\"$job.timer\"} - (systemd_timer_last_trigger_seconds{name=~\"$job.timer\"} offset 1s) > 0, 0, 1), \"name\", \"$1.service\", \"name\", \"(.*).timer\")) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Disk IO Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{device=~\"sd.*\"}[2m])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 17 },
   "options": {
    "content": "If the log panel is empty, it may be because the amount of lines is too high.T ry filtering a few jobs first."
   }
  },
  {
   "title": "Logs - $job",
   "type": "logs",
   "gridPos": { "h": 30, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{unit=~\"$job.*.service\"}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device!~\"ramfs|tmpfs|none\", mountpoint=~\"$mountpoints\"} - node_filesystem_avail_bytes{device!~\"ramfs|tmpfs|none\", mountpoint=~\"$mountpoints\"}",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "node_filesystem_size_bytes{device!~\"ramfs|tmpfs|none\", mountpoint=~\"$mountpoints\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[2m])) by (instance, mode)",
     "legendFormat": "{{instance}} -- {{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expression": "$available / $total", "type": "math" }
   ]
  }
 ]
}