name: "Documentation"
on:
  pull_request:
jobs:
  gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-conf: "system-features = nixos-test benchmark big-parallel kvm"
      - name: Setup Caching
        uses: cachix/cachix-action@v14
        with:
          name: selfhostblocks
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Test building docs
        run: |
          nix \
            --print-build-logs \
            --option keep-going true \
            --show-trace \
            build .#manualHtml
